/* Auto-generated by scripts/sync-portfolio.mjs — do not edit by hand */
export const portfolio = [
  {
    "id": "bringmebuds",
    "title": "BringMeBuds.ca",
    "category": "Cannabis delivery · Halifax",
    "url": "https://bringmebuds.vercel.app",
    "description": "Full shop rebuild — browse, cart, coupons, delivery logic. Mobile-first UX designed to reduce friction and complete more orders.",
    "tags": [
      "E-commerce UX",
      "Brand",
      "Engineering"
    ],
    "shots": [
      {
        "src": "/work/bringmebuds/01-home-desktop.png",
        "alt": "BringMeBuds.ca — Home Desktop",
        "caption": "Home Desktop",
        "featured": true
      },
      {
        "src": "/work/bringmebuds/02-shop-desktop.png",
        "alt": "BringMeBuds.ca — Shop Desktop",
        "caption": "Shop Desktop",
        "featured": false
      },
      {
        "src": "/work/bringmebuds/03-shop-mobile.png",
        "alt": "BringMeBuds.ca — Shop Mobile",
        "caption": "Shop Mobile",
        "featured": false
      },
      {
        "src": "/work/bringmebuds/04-product-desktop.png",
        "alt": "BringMeBuds.ca — Product Desktop",
        "caption": "Product Desktop",
        "featured": false
      }
    ]
  }
] as const;

export type PortfolioProject = (typeof portfolio)[number];
export type PortfolioShot = PortfolioProject['shots'][number];
