/* Auto-generated by scripts/sync-portfolio.mjs — do not edit by hand */
export const portfolio = [
  {
    "id": "bringmebuds",
    "title": "BringMeBuds.ca",
    "category": "Cannabis delivery · Halifax",
    "url": "https://bringmebuds.vercel.app",
    "description": "Full shop rebuild — browse, cart, coupons, delivery logic. Mobile-first UX designed to reduce friction and complete more orders.",
    "tags": [
      "E-commerce UX",
      "Brand",
      "Engineering"
    ],
    "shots": [
      {
        "src": "/work/bringmebuds/Screenshot%202026-05-18%20at%206.19.49%E2%80%AFPM.png",
        "alt": "BringMeBuds.ca — Screen 1",
        "caption": "Screen 1",
        "featured": true,
        "width": 2322,
        "height": 1750
      },
      {
        "src": "/work/bringmebuds/Screenshot%202026-05-18%20at%206.23.19%E2%80%AFPM.png",
        "alt": "BringMeBuds.ca — Screen 2",
        "caption": "Screen 2",
        "featured": false,
        "width": 1032,
        "height": 1768
      }
    ]
  },
  {
    "id": "handcash",
    "title": "HandCash",
    "category": "Bitcoin wallet · Payments",
    "url": "https://handcash.io",
    "description": "Wallet and payments product UI — consumer fintech flows built for clarity and speed.",
    "tags": [
      "Product UI",
      "Fintech",
      "Engineering"
    ],
    "shots": [
      {
        "src": "/work/handcash/Screenshot%202026-05-18%20at%206.21.02%E2%80%AFPM.png",
        "alt": "HandCash — Screen 1",
        "caption": "Screen 1",
        "featured": true,
        "width": 2322,
        "height": 1750
      },
      {
        "src": "/work/handcash/image.png",
        "alt": "HandCash — Image",
        "caption": "Image",
        "featured": false,
        "width": 816,
        "height": 1768
      }
    ]
  },
  {
    "id": "LilPoker",
    "title": "LilPoker",
    "category": "Games · Web",
    "url": "",
    "description": "Poker product interface — table-ready layouts and focused player flows.",
    "tags": [
      "Games",
      "UI/UX",
      "Engineering"
    ],
    "shots": [
      {
        "src": "/work/LilPoker/Screenshot%202026-05-18%20at%206.20.34%E2%80%AFPM.png",
        "alt": "LilPoker — Screen 1",
        "caption": "Screen 1",
        "featured": true,
        "width": 2322,
        "height": 1750
      }
    ]
  },
  {
    "id": "Soundbase.click",
    "title": "Soundbase.click",
    "category": "Audio · Web",
    "url": "https://soundbase.click",
    "description": "Music/audio platform UI — discovery, playback, and creator-facing surfaces.",
    "tags": [
      "Audio",
      "Web app",
      "Design"
    ],
    "shots": [
      {
        "src": "/work/Soundbase.click/Screenshot%202026-05-18%20at%206.21.48%E2%80%AFPM.png",
        "alt": "Soundbase.click — Screen 1",
        "caption": "Screen 1",
        "featured": true,
        "width": 2752,
        "height": 1768
      },
      {
        "src": "/work/Soundbase.click/Screenshot%202026-05-18%20at%206.22.35%E2%80%AFPM.png",
        "alt": "Soundbase.click — Screen 2",
        "caption": "Screen 2",
        "featured": false,
        "width": 1032,
        "height": 1768
      }
    ]
  },
  {
    "id": "BrainrotGamez",
    "title": "BrainrotGamez",
    "category": "Games · Web",
    "url": "",
    "description": "Playful game storefront and discovery experience with bold visuals and fast browse-to-play paths.",
    "tags": [
      "Games",
      "Web design",
      "Engineering"
    ],
    "shots": [
      {
        "src": "/work/BrainrotGamez/IMG_4137.PNG",
        "alt": "BrainrotGamez — IMG_4137",
        "caption": "IMG_4137",
        "featured": true,
        "width": 1170,
        "height": 2532
      },
      {
        "src": "/work/BrainrotGamez/Screenshot%202026-05-18%20at%206.18.50%E2%80%AFPM.png",
        "alt": "BrainrotGamez — Screen 2",
        "caption": "Screen 2",
        "featured": false,
        "width": 2100,
        "height": 1632
      }
    ]
  }
] as const;

export type PortfolioProject = (typeof portfolio)[number];
export type PortfolioShot = PortfolioProject['shots'][number];
